version: "3"

services:
  test:
    image: pggen_source
    environment:
      DB_URL: "postgres://postgres:test@postgres/postgres?sslmode=disable"
    links:
      - "postgres"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "test"
